version: "3.9" #ElianHD

services:

  zabbix:
    image: zabbix/zabbix-appliance:alpine-latest
    restart: unless-stopped
    ports:
      - "8082:80"
      - "10051:10051"
    environment:
      TZ: Europe/Paris
